name: Build Samsung M30 Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4

    - name: Set up build dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison build-essential curl flex git libssl-dev libncurses5-dev libncursesw5-dev libelf-dev ccache python3 unzip

    - name: Download Toolchain (aarch64)
      run: |
        git clone --depth=1 https://github.com/arter97/arm64-gcc.git gcc
        echo "TOOLCHAIN INSTALLED"

    - name: Compile Kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export CROSS_COMPILE=$(pwd)/gcc/bin/aarch64-linux-gnu-
        export PATH=$(pwd)/gcc/bin:$PATH

        make exynos7904_defconfig
        make -j$(nproc)

    - name: Upload Kernel Image
      uses: actions/upload-artifact@v4
      with:
        name: Image
        path: arch/arm64/boot/Image.gz
